"""Author-facing contracts decoded from the US executable.

Research, addresses and open questions live in research/SCRIPT_NATIVE_CONTRACTS.md.
This module only supplies prose; it does not alter the compiler's API catalog.
"""

CONTRACTS = {}
PARAM_TYPES = {}

def define(name, behavior, args=(), returns="1.", notes="", types=None, example=None):
    CONTRACTS[name] = dict(behavior=behavior, args=list(args), returns=returns,
                           notes=notes, evidence="Confirmed engine behavior",
                           source="../../research/SCRIPT_NATIVE_CONTRACTS.md")
    if types:
        PARAM_TYPES[name] = types.split()
    if example:
        CONTRACTS[name]['example'] = example

U = ('unit', 'Numeric unit handle from UnitGetByPID or another unit lookup. Zero means no unit; this is not a PID string or a memory address.')
P = ('pid', 'Exact PID_... character ID string.')
X = ('x', 'Map tile X coordinate, including the border; passed as a signed byte.')
Y = ('y', 'Map tile Y coordinate, including the border; passed as a signed byte.')
F = ('force', 'Force ID: 0 player, 1 enemy, 2 orderable ally, 3 other/green, 4 free pool, 5 reserve, 6 inactive, 7 special inactive.')
M = ('message_id', 'Message ID in a loaded message resource.')
R = ('rect_id', 'RID_... identifier of an existing rectangle/UI resource.')
T = ('duration_ms', 'Duration in milliseconds. Conversion to 60 Hz frames truncates fractional frames.')
EN = ('enabled', '0 disables; nonzero enables.')
VOID = 'No useful script result; call for its side effect.'
VALID = '1 for a valid unit; 0 if the handle is zero or its slot has no character.'

define('Check', 'Tests whether a base-conversation event is being evaluated for availability rather than being played.', returns='1 during the availability check; 0 while playing the conversation.', notes='In an availability check, return the condition and avoid dialogue, rewards, or other lasting changes. Use inside a base-conversation event.')
define('EnemyDeadCheck', 'Tests whether the enemy force list is empty.', returns='1 if empty; 0 if at least one enemy remains.')
define('PlayerDeadCheck', 'Tests whether the inactive force list is empty.', returns='1 if force 6 is empty; 0 otherwise.', notes='This does not mean “a player died.” Use GetDiedPlayerCount for the death-flagged count.')
define('GetDiedPlayerCount', 'Counts actors in force 6 whose death-record flag is set.', returns='Number of matching actors; can exceed 1.')
define('PlayerEscapeCheck', 'Tests whether every existing actor in player force 0 or reserve force 5 has the escaped flag.', returns='1 if all match, including when there are no matching actors; 0 if any has not escaped.')
define('PlayerEscapeCount', 'Counts escaped actors in player force 0 and reserve force 5.', returns='Number of escaped actors.')
define('EnemyUnitCheckByPID', 'Counts actors with the specified PID in the enemy force.', [P], 'Count, not a boolean.', types='charp')
for name, match in [('EnemyMonkCheck', 'class JID_PRIEST, JID_BISHOP, or JID_BISHOP_F'), ('EnemyTigerCheck', 'class JID_TIGER'), ('EnemySelfDefenceCheck', 'PID PID_12_SELFDEFENCE')]:
    define(name, f'Counts enemy-force actors with {match}.', returns='Number of matching enemies.')
define('PIDisAlive', 'Looks up a character’s current actor and checks that its dead flag is clear.', [P], '0 if no actor exists or it is dead; 1 otherwise.', 'An unused character definition alone is not a living actor.', 'charp')
define('GetRnd', 'Draws a random integer using the game random-number generator.', [('exclusive_max', 'Positive upper bound; the result is smaller than this value.')], 'Integer from 0 through exclusive_max - 1.', 'Consumes random state. Do not use zero or negative bounds.', 'int')
define('CheckAttackable', 'Tests whether this unit can reach a position from which its equipped weapon can attack an eligible enemy.', [U], '1 if an attack opportunity exists; 0 otherwise, including missing unit, no weapon, or disqualifying status.', 'Includes movement and weapon range; this is not a test of a particular target.', 'uint')

define('BMGetValue', 'Reads a signed 16-bit field from battle-map state.', [('field_index', 'Halfword index in battle-map state. Use an index from an existing matching chapter; this is not a named flag slot.')], 'Signed value from -32768 through 32767.', 'Advanced raw accessor; no bounds check. Prefer a dedicated accessor when available.', 'int')
define('BMSetValue', 'Writes a 16-bit field in battle-map state.', [('field_index', 'Same halfword index used by BMGetValue; not bounds-checked.'), ('value', 'Value to store. Only the low 16 bits are retained.')], 'The supplied value, before truncation.', 'Do not invent indices. This edits shared chapter state.', 'int int')
define('BMSetTerm', 'Replaces one battle-map term string.', [('term_index', 'Term slot from the original chapter; slots hold 12 bytes each.'), ('text', 'At most 11 encoded bytes plus the string terminator. Null leaves the term unchanged.')], notes='Copies without a length check. Use short ASCII text or count encoded bytes, not Unicode characters.', types='int charp')
define('Complete18', 'Ends a multipart chapter segment and selects its next chapter-flow state.', [('part', '1 selects continuation state 5; 2 selects 6; 3 selects 7. Other values select 0.')], notes='Special-purpose chapter 18 flow; not a general victory replacement.', types='int')
define('Comeback', 'Consumes the current event skip/cancel state and performs its cleanup.', returns='1 when skip/cancel cleanup ran; 0 when there was nothing to consume.', notes='This changes state. Do not replace it with a read-only condition or call repeatedly to “peek.”')

for name in ['Dialog', 'DialogDirect', 'DialogTutorial']:
    define(name, ('Opens a tutorial dialog' if name == 'DialogTutorial' else 'Opens a message dialog') + ' and suspends this script until the dialog process releases it.', [M], '0; this is not a failure indication.', 'Read DialogResult afterwards if the message presents a choice. DialogDirect uses the same opening behavior as Dialog in this build.', 'charp')
for count in [2, 3, 4]:
    define(f'Dialog{count}Items', f'Opens a choice dialog with {count} entries and suspends the calling script.', [(f'choice_{i+1}', f'Message ID for choice {i+1}, in display order.') for i in range(count)], '1 when accepted; 0 for an invalid message argument.', 'Read DialogResult after the dialog closes; the opening call does not return the choice.', ' '.join(['charp']*count))
for name in ['DialogResult', 'DialogGetRes']:
    define(name, 'Reads the last dialog result.', returns='Signed result byte: -1 before a result is selected; otherwise the dialog’s selected entry value.', notes='Read only after the dialog completes. Do not treat -1 as “yes” because it is nonzero; retain the choice mapping of the dialog you use.')
define('DialogSetDefault', 'Sets the default selection byte used by dialogs.', [('selection', 'Default choice value for the dialog being opened; only the low byte is retained.')], VOID, 'Set before opening the dialog. Use the same entry numbering as that dialog.', 'byte')
define('DefaultDieTalk', 'Looks up and starts the defeated unit’s default death message when that message exists. For player or inactive units it also selects death music.', returns='1 when a matching message exists; 0 otherwise.', notes='Requires a current defeated-unit context. It can reuse an existing talk process.')
define('DefaultEscapeTalk', 'Looks up and starts the current acting unit’s default escape message when available.', returns='0, including when a message was started.', notes='Requires a current acting-unit context. Follow the usual talk completion sequence.')
define('TalkEventDirect', 'Starts the supplied event message, or passes it to the existing conversation process.', [M], notes='Does not itself wait until every line has finished; use the normal TalkExist/TalkResume flow.', types='charp')

define('BGMResume', 'Restores map-music channel 0 to volume 100 over 200 ms and starts a 200 ms countdown on active event-music channels 1–3.', notes='Use when leaving an event-music sequence and returning to the map soundtrack.')
define('FRAME2MSEC', 'Converts a 60 Hz frame count to milliseconds.', [('frames', 'Frame count, typically nonnegative.')], 'frames × 16.666666, truncated to an integer.', types='int')
define('MSEC2FRAME', 'Converts milliseconds to 60 Hz frames.', [T], 'duration_ms ÷ 16.666666, truncated to an integer.', types='int')
for name, verb in [('WipeIn', 'in'), ('WipeOut', 'out')]:
    define(name, f'Starts a screen wipe {verb}.', [('duration_ms', 'Duration in milliseconds; a negative value uses 2000 ms.')], notes='Use WipeWait before work that requires the transition to finish.', types='int')
define('WipeEnd', 'Resets the screen-wipe state to idle.')
define('WipeWait', 'Suspends the script while a wipe-in or wipe-out transition is active.')
define('isWipe', 'Tests whether a wipe-in or wipe-out transition is active.', returns='1 while transitioning; 0 otherwise.')
define('Flash', 'Starts a colored screen flash.', [('red', 'Red component; clamped to 0–255.'), ('green', 'Green component; clamped to 0–255.'), ('blue', 'Blue component; clamped to 0–255.'), ('appear_ms', 'Appearance duration; negative uses 500 ms.'), ('disappear_ms', 'Disappearance duration; negative uses 500 ms.')], notes='Use FlashWait to wait for the transition.', types='int int int int int')
define('FlashWait', 'Suspends the script while the screen flash is transitioning.')
define('isFlash', 'Tests whether the screen flash is in either transition phase.', returns='1 while transitioning; 0 otherwise.')
define('WaitPressAnyKey', 'Suspends the calling script until the input-wait process completes after a key press.')
for name, feature in [('WarRecord', 'war-record display'), ('IndividualWarRecord', 'individual war-record display'), ('StaffRoll', 'staff credits')]:
    define(name, f'Starts the {feature} and suspends the calling script.', [T], notes='Intended for ending sequences with the corresponding display resources loaded.', types='int')

BUTTONS = ('buttons', 'Case-sensitive string: A B X Y Z L R are buttons, S is Start; 4/6/8/2 are left/right/up/down. Concatenate characters, e.g. "AB8". "*" selects every bit; other characters are ignored.')
define('PadSetMask', 'Adds buttons to the input mask used by event/tutorial control.', [BUTTONS], '0.', 'Pair with PadResetMask to restore those buttons when the sequence ends.', 'charp')
define('PadResetMask', 'Removes buttons from the input mask.', [BUTTONS], '0.', types='charp')
define('GetTutorial', 'Reads whether tutorial help is enabled in configuration.', returns='1 when enabled; 0 when disabled.')
define('Config_Tutorial', 'Resets the tutorial configuration block to defaults, including internal difficulty ID 1.', returns=VOID, notes='This is not a “show tutorial” toggle. It also overwrites difficulty and other settings; use the individual setters for a small change.')
define('Config_TutGet_sfx_vol', 'Reads the stored tutorial sound-effect volume byte.', returns='Stored volume value.')
define('Config_TutSet_sfx_vol', 'Stores the tutorial sound-effect volume and applies the settings.', [('volume', 'Volume byte; use the configuration’s existing range. Values are truncated to 8 bits.')], VOID, types='byte')
define('Config_TutSet_XinfoPage', 'Sets the tutorial information-page selection.', [('page', 'Page index stored as an 8-bit value; use a page available in this tutorial.')], VOID, types='byte')
for name, what in [('Config_TutSet_otheridoshowing', 'other-unit movement display'), ('Config_TutSet_terInfo', 'terrain information'), ('Config_TutSet_unitInfo', 'unit information')]:
    define(name, f'Sets the tutorial setting for {what}.', [('enabled', 'Exactly 1 enables it; every other value disables it.')], VOID, types='int')
for name, action in [('TutorialLearn', 'Marks a tutorial as learned'), ('TutorialForget', 'Clears a tutorial’s learned mark'), ('TutorialUnlock', 'Unlocks a tutorial'), ('TutorialLock', 'Locks a tutorial')]:
    define(name, action + '.', [('tutorial_id', 'Bit index of an existing tutorial entry; use its numeric ID, not its script export name.')], notes='Learned status and unlocked status are separate.', types='byte')
define('TutorialInitialize', 'Starts tutorial initialization and suspends the calling script until it completes.')
define('QueryLesson', 'Tests whether the active lesson has the given name.', [('lesson_name', 'Exact name of the active tutorial lesson.')], '1 on a match; 0 if no matching lesson is active.', types='charp')
define('TutShow', 'Starts a tutorial text display.', [('text_resource', 'Text resource expected by the existing tutorial display sequence.')], types='charp')

for name, action in [('DispPreLoadWholeForce', 'Queues battle-animation assets for'), ('DispLoadWholeForce', 'Loads display resources for'), ('DispFreeWholeForce', 'Releases display resources for')]:
    define(name, f'{action} every actor in a force list.', [F], notes='Does not change force membership or remove the actors.', types='int')
define('DisposGetGroupCenter', 'Computes the center of a named deployment group and writes its coordinates into two variables.', [('group', 'Existing deployment group name.'), ('out_x', 'Address of an integer local, written with the group-center X.'), ('out_y', 'Address of an integer local, written with the group-center Y.')], '0; read the output variables.', types='charp intp intp', example='var center_x = 0\nvar center_y = 0\nDisposGetGroupCenter("enemy", &center_x, &center_y)')
define('DisposWarp', 'Deploys a named reinforcement group using the warp deployment mode and suspends for active deployment motion.', [('group', 'Existing deployment group; create its records in the deployment data first.')], types='charp')
define('UnitGetByPID', 'Finds the current runtime actor for a character ID.', [P], 'Numeric unit handle, or 0 if absent.', 'A character can exist in the data without a current actor. Check the result before passing it to other calls.', 'charp')
define('UnitGetByPos', 'Finds an eligible visible actor occupying a map tile.', [X, Y], 'Numeric unit handle, or 0 if none is found.', 'Filters force membership and actor state; this is not a scan of every allocated actor.', 'int int')
define('UnitGetRace', 'Reports the unit’s beorc/laguz transformation category.', [U], '0 for beorc or an invalid unit; 1 for untransformed laguz; 2 for transformed laguz.', types='uint')
for name, animated in [('InstantUnitTransform', False), ('UnitTransform', True)]:
    define(name, 'Changes a unit to the requested transformed/untransformed state' + (' with its transformation animation.' if animated else ' immediately and refreshes its display.'), [U, ('transformed', '0 requests untransformed; nonzero requests transformed. This is a desired state, not a toggle.')], '1 if ' + ('an animation is scheduled' if animated else 'the state changes') + '; 0 for invalid unit or already matching state' + ('; the skip path applies the change immediately but returns 0.' if animated else '.'), 'Use only on a compatible laguz unit.' + (' Synchronize with the scene’s unit-motion wait.' if animated else ''), 'uint char')
define('UnitSetFixed', 'Sets or clears the unit’s fixed-state flag.', [U, EN], VALID, types='uint int')
define('CpClrNoMoveFlag', 'Clears the two no-move control bits from a unit’s AI state.', [U], 'Updated AI control word; 0 for an invalid unit. A zero result can also mean all bits are now clear.', types='uint')
define('UnitGetEquipWepI', 'Gets the active equipped-weapon slot index.', [U], 'Weapon slot index, or -1 when none is active; 0 for an invalid unit.', 'Validate the unit first because 0 is also a valid slot.', 'uint')
define('UnitGetEquipAccI', 'Gets the active accessory slot in the combined inventory numbering.', [U], 'Accessory slot index 4–7, or -1 when none is active; 0 for an invalid unit.', types='uint')
SLOT = ('slot', 'Inventory index: 0–3 weapon slots, 4–7 item/accessory slots. Never pass an index outside 0–7.')
define('UnitQueryEquip', 'Tests the equipped bit of an inventory slot.', [U, SLOT], '1 if the slot’s equipped bit is set; 0 otherwise or for an invalid unit.', types='uint int')
define('UnitCanUseIt', 'Checks whether the unit can use the item in the specified inventory slot.', [U, SLOT], 'Use predicate; 0 for an invalid unit or an empty slot.', types='uint int')
define('UnitReplaceItem', 'Replaces the selected inventory slot using an item ID.', [U, SLOT, ('iid', 'Existing IID_... item definition.')], VALID, 'Provide a valid slot and item ID; this is not an “add to first empty slot” operation.', 'uint int charp')
for name, desc in [('UnitSetCpHealSeq', 'healing AI sequence'), ('UnitSetCpMTypeID', 'MTYPE AI table')]:
    define(name, f'Changes the unit’s {desc} by resource name.', [U, ('resource_id', f'Existing name of a {desc} resource.')], VALID, 'If the resource name is not found, the old setting remains unchanged even though the call returns 1.', 'uint charp')
define('UnitGetMoveCost', 'Reads this unit’s movement cost for a terrain-table entry.', [U, ('terrain_index', 'Index in the movement-cost table for the unit’s class; not a map X or Y coordinate.')], 'Movement cost; -1 when the terrain cost exceeds 30000 (impassable); 0 for invalid unit.', 'No terrain-index bounds check; use a valid terrain entry.', 'uint int')
define('UnitPairup', 'Links two actors using the game’s carrying/pairing operation, first moving the second actor to the tile right of the first.', [('carrier', U[1]), ('carried', U[1])], '1 for two valid actors; 0 otherwise.', 'Changes positions and refreshes movement ranges. This is the FE9 carry relationship, not a later game’s Pair Up combat system.', 'uint uint')
define('UnitTackle', 'Moves the target away from the acting unit and starts shove/smite motion.', [('acting_unit', U[1]), ('target_unit', U[1]), ('distance', 'Positive displacement in tiles; normally 1 for shove, 2 for smite. Use aligned adjacent units.')], '1 if motion is started; 0 for invalid units or the skip path. The skip path still moves the target immediately.', 'Does not itself validate that the destination is legal. Use the scene’s unit-motion wait before dependent actions.', 'uint uint int')
define('ItemGetIndex', 'Resolves an item ID to its numeric item index.', [('iid', 'Existing IID_... item ID string.')], 'Item index; 0 if the item ID is not found.', types='charp')
define('MindGetMind', 'Reads the current map-action ID.', returns='Action ID byte.', notes='Requires the event’s map-action context; this does not identify the acting unit.')
define('MindGetMoney', 'Adds gold to the party and starts a reward notification associated with the current acting unit.', [('amount', 'Gold amount added to the current total.')], '0; not a failure code.', 'Use in an event with a valid acting-unit context.', 'int')

define('UnitSet', 'Writes one of the supported mutable unit fields.', [U, ('field', '6 = level; 7 = experience; 8 = raw transformation gauge; 13 = current HP; 24 = biorhythm battle counter; 38 = group id (army-name index into GroupData; 0 leaves it unchanged). Other selectors do not write a field.'), ('value', 'New value. Level/gauge use a byte; counter uses 16 bits. HP is clamped by the unit HP setter.')], 'Supplied value for a valid unit, even for an unsupported selector; 0 for invalid unit or selector 0.', 'This is not a general stat editor: use dedicated stat calls for strength, magic, etc. UnitGet supports more fields than UnitSet.', 'uint int int')
define('UnitGet', 'Reads a selected property of a runtime unit.', [U, ('field', '1 = next unit handle in force list; 2 = previous handle; 4 = carried/linked unit handle; 5 = force; 6 = level; 7 = experience; 8 = transform gauge (adds 100 while transformed); 9/10 = tile X/Y; 11 = biorhythm phase × 100; 12/13 = maximum/current HP; 14–20 = strength, magic, skill, speed, luck, defense, resistance; 21 = build; 22 = movement; 23 = terrain avoid bonus; 24 = biorhythm battle counter; 35 = AI behavior type; 36/37 = character/class index; 38 = group id (army-name index into GroupData); 39–46 = HP/strength/magic/skill/speed/luck/defense/resistance caps.')], 'Selected value; 0 for an invalid unit or unsupported selector.', 'Use the listed selectors. Some additional engine selectors are not suitable for general authoring yet. Coordinates and stats can be signed; missing linked-unit handles are 0.', 'uint int', example='var unit = UnitGetByPID("PID_IKE")\nif unit != 0:\n    UnitSet(unit, 13, UnitGet(unit, 12))')

define('SetFragile', 'Adds a breakable terrain entry with the requested HP.', [X, Y, ('hp', 'Initial and current HP, stored as a byte (0–255).')], types='char char byte')
define('SetPit', 'Adds a pit terrain entry at the given tile.', [X, Y], types='char char')
define('SetShooter', 'Adds a ballista/shooter terrain entry initialized from an item definition.', [X, Y, ('variant', 'Shooter terrain subtype; preserve the variant used by the matching map object.'), ('iid', 'Valid shooter IID_... item. Initializes the shooter’s item index and remaining uses.')], notes='Requires matching map geometry. An invalid item name is unsafe.', types='char char byte charp')
define('ShooterBulletCheck', 'Totals spent ballista shots inside the active map bounds using five shots as the initial baseline.', returns='Sum of (5 − remaining uses) for each shooter terrain entry.', notes='This is spent ammunition, not remaining ammunition. Custom shooters with more than five uses can produce negative contributions.')
define('SetRoofEnable', 'Changes the enabled state of the roof section found at the supplied map position and refreshes the map.', [X, Y, EN], '1 if a roof entry is found; 0 otherwise.', types='int int char')
for name, light in [('SetAmbient', 'ambient'), ('SetDiffuse', 'diffuse')]:
    define(name, f'Sets map {light} lighting color, refreshes the map and yields the script.', [('red', 'Red component, 0–255.'), ('green', 'Green component, 0–255.'), ('blue', 'Blue component, 0–255.')], notes='Components are truncated to bytes, not clamped. Alpha is fixed to 255.', types='byte byte byte')
define('SetCamSuspend', 'Sets the camera-suspension flag for map scenes.', [EN], types='int')
define('SetOnBtFocus', 'Enables or disables automatic battle-focus behavior.', [EN], types='int')
define('SetPullCursor', 'Enables or disables automatic cursor pulling.', [EN], types='int')
define('SetSepia', 'Changes the sepia scene effect setting.', [('enabled', 'Use 1 to start the sepia effect; 0 to remove it. Other values also take the removal branch.')], types='byte')
define('UnitSetHold', 'Changes the shared scene unit-hold setting.', [EN], notes='Applies to scene state, not one unit. Restore 0 when the hold sequence ends.', types='int')
define('HidePrim2D', 'Starts or ends the scene process that hides 2D primitives.', [('hidden', 'Nonzero starts hiding; 0 removes the hiding process.')], types='int')
define('SetWhiteBackdrop', 'Starts the solid-white backdrop process.')
define('RemoveBackdrop', 'Removes the backdrop process.')
define('DeleteNoticeFrame', 'Removes the active E_NoticeFrame highlight frame.', returns='0.')
define('BeginMapHoldCursor', 'Starts the map cursor-hold process.', returns='0.')
define('EndMapHoldCursor', 'Ends the map cursor-hold process.', returns='0.')
define('SallyAddByPos', 'Appends a deployment-selection position.', [X, Y], types='char char')
define('SallySetByPos', 'Clears the deployment-selection position list, then adds this position.', [X, Y], notes='Repeated calls replace the list; use SallyAddByPos to append additional positions.', types='char char')
define('SelectAuxiliary', 'Starts the auxiliary-unit selection flow for a deployment group and suspends the calling script.', [('group', 'Existing deployment group name.')], '1 when accepted; 0 for an invalid group argument.', types='charp')

CURVE = ('curve', '0 linear; 1 quadratic ease-in; 2 cubic ease-in; 3 quartic ease-in; 4 quadratic ease-out; 5 cubic ease-out; 6 quartic ease-out; 7–9 oscillating/bouncing curves; 10 cosine ease-in/out; 11 sine ease-out; 12 cosine ease-in.')
define('intplGetValue', 'Computes one interpolated value without starting an animation.', [CURVE, ('start', 'Value at progress 0.'), ('end', 'Value at progress total.'), ('progress', 'Current progress; use the same units as total, normally within 0–total.'), ('total', 'Total progress span. Zero returns end.')], 'Interpolated value truncated to an integer; unsupported curve gives 0 when total is nonzero.', 'Does not clamp progress. Oscillating modes 8–9 also depend on the absolute time scale.', 'int int int int int', example='var halfway = intplGetValue(0, 0, 100, 50, 100)\n# halfway is 50')
define('RectAdjustBoundary', 'Aligns a rectangle’s source image inside the 608 × 448 layout area.', [R, ('alignment', 'Numeric-keypad layout: 7/8/9 top left/center/right, 4/5/6 middle, 1/2/3 bottom. Other values leave position unchanged.')], '1 if the rectangle exists; 0 otherwise.', 'Uses the image’s unscaled bounds; this is an alignment selector, not a pixel offset.', 'charp int')
define('RectGet', 'Reads a rectangle property and truncates it to an integer.', [R, ('property', '0 = X; 1 = Y; 5 = horizontal scale; 6 = vertical scale; 7 also reads horizontal scale. Other properties depend on the rectangle type.')], 'Property value, or 0 if the rectangle is absent. Scale is the raw factor: 100% reads as 1, and 50% truncates to 0.', 'RectSet takes scale percentages, while RectGet returns the raw factor. Do not round-trip percentage values through this getter.', 'charp byte')
define('RectSet', 'Sets a rectangle property immediately.', [R, ('property', '0 = X; 1 = Y; 5 = horizontal scale; 6 = vertical scale; 7 = both scales; 9 = fade/opacity byte. Keep other selectors from the matching resource’s existing sequence.'), ('value', 'Position in layout coordinates; scale in percent (100 = normal size); opacity 0–255. Byte properties wrap rather than clamp.')], '1 if the rectangle exists; 0 otherwise.', types='charp int int')
define('RectSetCurve', 'Animates one rectangle property between two values.', [R, ('property', 'Same selector as RectSet.'), CURVE, ('start', 'Starting value; 123456789 means use the current value. Scale properties use percentages.'), ('end', 'Final value in the same units as start.'), ('frames', 'Duration in frames, not milliseconds. Use a positive count.')], '1 if the rectangle exists; 0 otherwise.', 'Equal endpoints set immediately. Event skipping applies the final value immediately. This starts animation without waiting for it.', 'charp int int int int int')
define('RectSetPos', 'Sets a rectangle or world-map image’s position immediately.', [R, ('x', 'Layout-space X coordinate, not map tile X.'), ('y', 'Layout-space Y coordinate.')], '1 if the rectangle/map exists; 0 otherwise.', types='charp int int')
define('RectMove', 'Animates a rectangle/world-map image so a source point is centered at (304, 240) at the requested scale.', [R, ('focus_x', 'Source-image X coordinate to center.'), ('focus_y', 'Source-image Y coordinate to center.'), ('scale_percent', 'Uniform scale; 100 = normal size.'), ('frames', 'Duration in frames; values below 1 become 1.'), CURVE], '1 if the target exists; 0 otherwise.', 'Final position is (304 − focus_x × scale/100, 240 − focus_y × scale/100). This starts animation; it does not wait.', 'charp int int int int int')
define('RectMoveOffset', 'Animates a rectangle/world-map image to an explicit offset and restores its scale to 100%.', [R, ('x', 'Final layout-space X offset.'), ('y', 'Final layout-space Y offset.'), ('frames', 'Duration in frames; values below 1 become 1.'), CURVE], '1 if the target exists; 0 otherwise.', types='charp int int int int')

for name, action in [('JyokyoMapCapture', 'Captures the status-map display and suspends the script while capture completes'), ('JyokyoMapDelete', 'Deletes the status-map display'), ('JyokyoMapHide', 'Hides the status-map display'), ('JyokyoMapShow', 'Starts the status-map display'), ('JyokyoMapEnemyOn', 'Enables enemy markers on the status map'), ('JyokyoMapPlayerOn', 'Enables player markers on the status map')]:
    define(name, action + '.')
define('IsE3Version', 'Tests the E3/demo-build condition in this US executable.', returns='0, always.')
define('report', 'Writes text to the game’s debug-report output.', [('text', 'Plain diagnostic string. Avoid printf format placeholders because no additional formatting arguments can be supplied.')], '1 for an accepted string; 0 otherwise.', 'Does not show an in-game dialogue box.', 'charp')
define('ArenaDump', 'Prints memory-arena usage to debug output.', returns=VOID, notes='Useful for debugging resource-heavy scripts; it does not display an in-game menu.')
define('dump', 'Prints all eight force lists and their units to debug output.', returns=VOID, notes='Useful for checking unit membership; no gameplay changes.')

G = ('map_id', 'RID_GMAP_... resource ID of a world-map image already built for this scene.')
GI = ('index', 'Zero-based slot or resource entry index, as specified by this operation. Use only indices supported by the loaded world-map resource.')
GRET = '1 when the loaded map accepts the operation; 0 if the map is missing, the argument is invalid, or the event is being skipped.'
for name, action in [('GMapFlagMarkOffAll', 'Removes all flag markers'), ('GMapPointOffAll', 'Removes all point markers'), ('GMapRegionOffAll', 'Turns off all region overlays')]:
    define(name, action + ' on a world-map image.', [G], GRET, types='charp')
for name, action, target in [
    ('GMapFlagMarkOff', 'Turns off', 'flag marker'), ('GMapPointOff', 'Starts removal of', 'point marker'),
    ('GMapPenDraw1Seq', 'Starts drawing', 'pen sequence'), ('GMapPenReset', 'Resets', 'pen sequence'),
    ('GMapRegionOn', 'Turns on', 'region overlay'), ('GMapRegionOnSkipFlash', 'Turns on without its initial flash', 'region overlay'),
    ('GMapRegionOff', 'Turns off', 'region overlay'), ('GMapRegionFlashOnce', 'Requests a single flash of', 'region overlay')]:
    define(name, f'{action} the selected {target} on a world-map image.', [G, ('index', f'Index of the {target} in this world-map resource; not a chapter number.')], GRET, types='charp int')
define('GMapPenDispOnOff', 'Shows or hides the world-map pen overlay.', [G, EN], GRET, types='charp int')
define('GMapPenDarkOnOff', 'Changes the dark-display flag for one world-map pen sequence.', [G, ('sequence', 'Pen sequence index in the loaded resource.'), EN], GRET, types='charp int int')
define('GMapRegionFlashOnOff', 'Enables or disables the flashing flag for a world-map region.', [G, ('region', 'Region index in the loaded resource.'), EN], GRET, types='charp int int')
define('GMapPenDrawWait', 'Suspends this script until the world-map pen drawing operation completes.', [G], GRET, types='charp')
define('GMapFlagMarkOn', 'Creates or resets a flag marker on a world-map image.', [G, ('index', 'Flag-marker slot to use; reuse the same slot to replace its marker.'), ('x', 'X in world-map image coordinates.'), ('y', 'Y in world-map image coordinates.'), ('style', 'Marker style byte. Use an available style from the matching map scene.')], GRET, types='charp int short short byte')
define('GMapPointOn', 'Creates a colored point marker on a world-map image.', [G, ('index', 'Point-marker slot to use.'), ('x', 'X in world-map image coordinates.'), ('y', 'Y in world-map image coordinates.'), ('scale_percent', 'Marker scale; 100 = normal size.'), ('rgb', 'Packed RGB integer, for example 0xFF0000 for red. Alpha is fixed to 255.')], GRET, types='charp int int int int uint')

ARROW = ('arrow_id', 'Arrow slot index. Use a slot supported by the existing scene; this index is not bounds-checked.')
define('EventArrowAppend', 'Adds a timed waypoint to a map-event arrow’s path.', [ARROW, ('time_ms', 'Waypoint time in milliseconds, converted to frames and sorted into the path.'), X, Y, ('height', 'Map-space height. A value below -999 samples the terrain at the tile center, subtracts 1, and truncates to an integer.')], notes='X/Y are centered on the tile by adding 0.5. Build the path before EventArrowStart; use an existing path’s slot and waypoint limits.', types='int int int int int')
define('EventArrowColor', 'Sets the arrow’s RGBA color.', [ARROW, ('red', '0–255.'), ('green', '0–255.'), ('blue', '0–255.'), ('alpha', '0 transparent; 255 opaque.')], notes='Values are stored as bytes; they wrap rather than clamp.', types='int byte byte byte byte')
define('EventArrowFocus', 'Changes the arrow’s focus-following flag.', [ARROW, EN], types='int int')
define('EventArrowStart', 'Starts an arrow path transition from its current progress using the supplied time.', [ARROW, T], notes='Configure waypoints first; use EventArrowWait before dependent work.', types='int int')
define('EventArrowFadeOut', 'Requests fade-out of the selected map-event arrow.', [ARROW], types='int')
define('EventArrowDelete', 'Deletes the map-event arrow process and all of its arrows.')
define('EventArrowWait', 'Suspends the script while map-event arrows are animating.', returns='1 in ordinary playback; 0 during event skipping.')
define('EventQuake', 'Starts a repeating camera shake.', [('strength', 'Shake intensity; 0 produces no sustained shake.'), ('period_ms', 'Length of one shake cycle in milliseconds, truncated to frames; a converted value of 0 becomes one frame.'), ('cycles', 'Positive number of cycles; 0 or negative repeats until stopped.')], notes='The second argument is one cycle’s duration, not the total duration. EventQuakeStop ends a repeating shake.', types='int int int')
define('EventQuakeStop', 'Requests the active camera shake to stop.')
define('EffectPlay', 'Loads and spawns a named scene effect at the supplied position.', [('effect_id', 'Existing EID_... effect resource.'), ('x', 'Map tile X for a map-space effect; direct effect-space X for effects configured in another coordinate mode.'), ('y', 'Map tile Y for a map-space effect; direct effect-space Y for effects configured in another coordinate mode.')], '1 when scheduled; 0 during event skipping.', 'Map-space effects use the tile center and terrain height. The resource determines coordinate mode. The script waits for the loading/spawn process, not necessarily the full effect lifetime.', 'charp int int')
define('CreateNoticeFrame', 'Creates or updates an animated rectangular highlight around a screen area.', [('x', 'Screen-space left edge.'), ('y', 'Screen-space top edge.'), ('width', 'Width in screen coordinates.'), ('height', 'Height in screen coordinates.')], '0.', 'Remove it with DeleteNoticeFrame. Coordinates are not map tiles.', 'int int int int')
define('CreateNoticeLFrame', 'Creates or updates an animated six-edge L-shaped screen highlight.', [('x', 'Left edge of the complete shape.'), ('y', 'Top edge of the complete shape.'), ('width_1', 'First horizontal segment length.'), ('width_2', 'Additional horizontal segment length; total width is width_1 + width_2.'), ('height_1', 'First vertical segment length.'), ('height_2', 'Additional vertical segment length; total height is height_1 + height_2.'), ('orientation', '0 cuts out the bottom-left part; nonzero cuts out the top-right part.')], '0.', 'All six numeric dimensions are screen coordinates. The fifth and sixth arguments are lengths, not RGBA colors. Remove with DeleteNoticeFrame.', 'int int int int int int int')

define('NetuzoInit', 'Clears all 32 scripted-strike override slots and resets the scripted-battle counters.', notes='Call before configuring a new scripted battle; prevents stale overrides from the preceding sequence.')
define('NetuzoSet', 'Configures outcome and combat-effect overrides for one scripted strike.', [('strike_index', 'Zero-based strike slot, 0–31. No bounds check.'), ('outcome_flags', '0 uses normal hit/critical resolution; bit 1 forces a hit, bit 2 a critical, bit 4 a miss. Hit takes precedence over critical, which takes precedence over miss.'), ('effect_flags', 'Combat-effect bitmask, not damage. 0 = no forced effects; 0x0001 halves damage rounded up; 0x0002 heals attacker by damage; 0x0004 uses half defender defense; 0x0010 forces lethal-strength damage; 0x0080 prevents counter; 0x0100 sets damage to zero; 0x0200 sets damage to half defender HP; 0x0400 prevents this strike killing the defender. Additional special-skill flags should be retained from the matching battle.')], notes='Combine effects only deliberately; later damage modifiers can change earlier ones. Set the combatants’ stats/equipment to control ordinary damage.', types='int byte ushort')
define('NetuzoBattle', 'Resolves and starts a scripted combat exchange between two actors, then suspends the script for the battle process.', [('attacker', 'Valid attacker unit handle; no null-unit guard.'), ('defender', 'Valid defender unit handle; no null-unit guard.'), ('event_battle', '0 clears the event-battle flag; nonzero sets it. Shared battle/death dialogue helpers test this flag to choose their event behavior.')], notes='Use NetuzoInit and NetuzoSet first when forcing strikes. Requires valid combatants and battle resources. This changes combat state; it is not a visual-only preview.', types='uint uint char')
for name, action in [('BeginFinale', 'Enables'), ('EndFinale', 'Disables')]:
    define(name, f'{action} finale mode and its input mask for A/B/X/Y/Z/L/R/Start.', notes='Pair BeginFinale and EndFinale around ending sequences; neither call starts the credits by itself.')
define('SetSight', 'Sets the fog-of-war/sight mode, recalculates map ranges and refreshes the map.', [('mode', 'Sight-mode byte; internal difficulty other than 1 forces this to 0. Preserve the chapter’s supported mode values.'), ('unused', 'Ignored by this US implementation; pass 0 when creating a new call.')], notes='The signature still requires two arguments even though the second is ignored. This controls gameplay visibility, unlike SetFog’s rendering effect.', types='byte int')
define('SetFog', 'Sets the map’s rendering fog and refreshes its render state.', [('fog_type', 'Rendering fog mode byte. Use the map’s existing supported mode; 0 disables fog.'), ('start_distance', 'Signed-byte fog start distance in map units; converted by 5 × map scale for rendering.'), ('end_distance', 'Signed-byte fog end distance in the same units.'), ('red', 'Fog color red, 0–255.'), ('green', 'Fog color green, 0–255.'), ('blue', 'Fog color blue, 0–255.')], notes='This changes visual distance fog, not which tiles units can see. Use SetSight for gameplay visibility.', types='byte char char byte byte byte')
define('SetWeather', 'Changes the map weather byte and refreshes weather, lighting and visibility rendering.', [('weather', 'Weather ID supported by the loaded chapter. Preserve the matching map’s existing IDs when adding effects.')], notes='The script yields after refreshing. Weather effects depend on the map’s resources.', types='byte')
define('MCResult', 'Reads the last memory-card operation status.', returns='Memory-card status code; it is not a boolean.', notes='Use only in a matching save/load workflow after its asynchronous operation completes. This call does not start a save.')
define('SysGetRound', 'Reads the playthrough ordinal from the clear-data record.', returns='1 plus the number of consecutive occupied clear-data slots, from 1 to 31.', notes='Used by trial-map unlock helpers; not the current map turn.')
define('SallyGetSurplus', 'Reads the deployment surplus recorded when the deployment-selection flow finishes.', returns='Surplus byte; initialized to 0 at chapter start.', notes='The stored value is the greater of the selection flow’s minimum and (deployment allowance − selected player count). Read after selection completes, not while editing the selection.')
for name, action in [('ArcLoad', 'Loads'), ('ArcFree', 'Releases one reference to')]:
    define(name, f'{action} a relocatable game resource.', [('resource_path', 'Game resource path, for example "mess/tut.m". Use lowercase and the same path for its matching load/release.')], notes='Keep load and release ownership balanced. ArcFree may lowercase the supplied path in place. Do not release a resource while another sequence still uses it.', types='charp')

CAP_POS = [('x', 'Screen-space caption X coordinate.'), ('y', 'Screen-space caption Y coordinate.')]
CAP_TIMES = [('appear_ms', 'Appearance duration in milliseconds.'), ('hold_ms', 'Time fully displayed, in milliseconds.'), ('disappear_ms', 'Disappearance duration in milliseconds.')]
define('TimeiShow', 'Shows a timed location-name caption.', CAP_POS + [M] + CAP_TIMES, '1 when accepted; 0 for an invalid message argument.', 'Timing is converted to 60 Hz frames. This schedules the caption without waiting through its whole lifetime.', 'short short charp int int int')
define('TimeiShowHold', 'Shows a location-name caption that stays visible until explicitly released.', [('caption_id', 'Byte slot ID for later TimeiShowHoldOff; avoid 255, which is used as the all-captions selector.')] + CAP_POS + [M, ('appear_ms', 'Appearance duration in milliseconds.')], '1 when accepted; 0 for invalid message.', types='byte short short charp int')
define('TimeiShowHoldOff', 'Starts disappearance of the held caption with this ID.', [('caption_id', 'ID passed to TimeiShowHold or TimeiShowHoldGMap.'), ('disappear_ms', 'Disappearance duration in milliseconds.')], types='byte int')
define('TimeiShowHoldOffAll', 'Starts disappearance of every held caption.', [('disappear_ms', 'Disappearance duration in milliseconds.')], types='int')
define('TutShowKari', 'Shows a temporary tutorial caption with matching appearance and disappearance durations.', CAP_POS + [M, ('fade_ms', 'Duration of each fade, in milliseconds.'), ('hold_ms', 'Fully visible time in milliseconds.')], '1 when accepted; 0 for invalid message.', types='short short charp int int')

WIDTH_EXTRA = ('extra_width', 'Additional width added to the caption’s text-sized background, in screen coordinates. Use 0 for the normal width.')
define('TimeiShowGMap', 'Shows a timed location caption using the world-map caption style.', CAP_POS + [WIDTH_EXTRA, M] + CAP_TIMES, '1 when accepted; 0 for invalid message.', 'The caption is positioned in screen coordinates; this call does not take a map ID.', 'short short short charp int int int')
define('TimeiShowHoldGMap', 'Shows a held location caption using the world-map caption style.', [('caption_id', 'Byte ID used by TimeiShowHoldOff; avoid 255.')] + CAP_POS + [WIDTH_EXTRA, M, ('appear_ms', 'Appearance duration in milliseconds.')], '1 when accepted; 0 for invalid message.', types='byte short short short charp int')
define('TTPMInit', 'Clears the 32 registered terrain-motion path slots.', notes='Call before registering rock-motion paths for a chapter. Existing rocks referring to these slots need their paths registered again.')
define('TTPMEntry', 'Stores a terrain-motion path in the first free path slot.', [('path', 'Persistent direction string used by terrain motion, such as a string of numeric-keypad directions from the existing chapter. The string is retained, not copied.')], 'Allocated slot index 0–31; -1 if the table is full.', 'Pass the returned slot to SetRock. Use a string literal that remains loaded while the rock exists.', 'charp')
define('SetRock', 'Adds a rolling-rock terrain entry connected to a registered motion path.', [X, Y, ('direction', 'Initial direction code used by the matching rock setup.'), ('path_index', 'Slot returned by TTPMEntry, 0–31. Register the path first.')], notes='The map needs compatible rock geometry. This registers the terrain entry; it does not immediately roll the rock.', types='char char byte byte')
define('AddTT', 'Adds a raw temporary-terrain entry at a tile.', [X, Y, ('type', 'Terrain-entry type. Prefer SetFragile (4), SetShooter (7), SetRock (10), or SetPit when available.'), ('subtype', 'Type-specific subtype byte.'), ('value_1', 'First type-specific state byte.'), ('value_2', 'Second type-specific state byte.')], notes='Low-level operation: use the dedicated constructors for normal authoring. All four control/state values are bytes; two remaining state bytes are zeroed. It does not create map geometry.', types='char char byte byte byte byte')
for name, desc in [('GetMapHeightBase', 'base terrain height'), ('GetMapHeight', 'alternate terrain-surface height')]:
    define(name, f'Samples the {desc} at the supplied map coordinates.', [X, Y], 'Sampled height multiplied by the event-camera precision factor, then truncated to an integer. Precision defaults to 1.', 'Use with event-camera coordinates; this is a height value, not a flattened tile index.', 'char char')
for name, axis in [('GetFukiPosX', 'X'), ('GetFukiPosY', 'Y')]:
    define(name, f'Reads the {axis} coordinate of the active tutorial speech-bubble display.', returns=f'Signed {axis} coordinate; 0 if the display process is absent.', notes='Useful for positioning tutorial graphics around the active bubble; 0 is also a valid position.')
define('RectLeave', 'Creates a rectangle/world-map image without attaching it to the current event as its parent.', [R], '0.', 'Unlike RectBuild, it passes no event parent. Explicitly remove it with RectKill when it is no longer needed; it is not a synonym for deleting the rectangle.', 'charp')
define('CmLoadScript', 'Loads a CMB script module and makes its exported functions available.', [('script_path', 'Existing game resource path to a .cmb module. Use the path form already used by the project’s module-loading sequence.')], notes='Load before calling its exports; free modules in reverse load order with CmFreeScript. This loads a compiled game resource, not a .fe9s editor file.', types='charp')
define('CmSleepScript', 'Suspends a module’s event enumeration and temporarily removes its exported functions.', [('module_name', 'Name stored in the loaded CMB header. Empty string or 0 selects the last-loaded module.')], '1 when a module is found; 0 if a named module is absent.', 'The module stays allocated. CmWakeupScripts restores sleeping modules and their exports.', 'charp')
for name in ['UnitPutToWarehouse', 'UnitItemSendtoWarehouseAll']:
    define(name, 'Transfers all eight of a unit’s inventory slots to storage, clears the original slots, and compacts the inventory.', [U], VALID, 'The two function names are aliases. The original slot is cleared after each transfer attempt; make sure storage has enough capacity before using this on valuable items.', 'uint')
define('SetGrid', 'Sets the map-grid display intensity or restores the value saved when scene settings were created.', [('percent', '0–100 grid intensity; values above 100 become 100. A negative value restores the saved grid setting if scene settings exist.')], types='int')
define('SetCircle', 'Enables or disables the scene’s unit-circle display setting.', [EN], types='int')
define('UnitWalkSlow', 'Enables or disables slow walking for subsequent scene movement.', [EN], notes='This is shared scene state. Restore 0 when the slow-walk sequence ends.', types='int')
define('UnitWalkDir', 'Sets the direction bits used by subsequent scene walking.', [('direction', 'Low four direction bits: 1 negative X, 2 positive X, 4 positive Y, 8 negative Y. Other bits are discarded.')], notes='Shared movement setting, not the direction of a unit passed to this call.', types='ushort')
define('SetOutLink', 'Enables or disables the outer-link portion of the map-link grid and rebuilds that grid.', [EN], notes='Shared scene setting. Restore the chapter’s setting after staged movement that changes it.', types='int')
define('MapGetTerrain', 'Reads the terrain ID stored at a map tile.', [X, Y], 'Terrain ID byte.', 'Use coordinates inside the allocated map grid; there is no coordinate bounds check.', 'char char')
define('MapGetUnit', 'Reads the occupancy-grid unit handle at a tile.', [X, Y], 'Unit handle byte; 0 for an empty cell.', 'This reads the occupancy grid directly. Use valid map coordinates.', 'char char')
define('MapGetSight', 'Reads the visibility-grid byte at a tile.', [X, Y], 'Stored visibility value.', 'Use valid map coordinates and the chapter’s existing visibility comparisons; this does not recalculate sight.', 'char char')
define('Fade', 'Starts a screen transition.', [('mode', '0 = clear screen immediately; 1 = solid black; 2 = fade in from black; 3 = fade out to black; 4 = solid white; 5 = fade in from white; 6 = fade out to white; 7 = captured-screen transition.'), ('duration_ms', 'Duration in milliseconds; negative uses 500 ms.')], notes='Use FadeWait before starting another transition. During event skipping, transitions go directly to their final state.', types='byte int')
for name, action in [('RectFadeIn', 'Fades in'), ('RectFadeOut', 'Fades out'), ('RectFadeOutDelete', 'Fades out and then deletes')]:
    define(name, f'{action} a rectangle.', [R, ('frames', 'Duration in frames. Ordinary rectangles keep only the low byte: use 1–255. World-map fade-in/out uses a signed 16-bit duration, with a minimum of 1.')], '1 if the rectangle exists; 0 otherwise.', 'Starts the animation without waiting. RectFadeOutDelete uses the ordinary-rectangle path.', 'charp int')

define('BMSetTanto', 'Sets who controls each of the four active map forces.', [(name, 'Control mode: 0 none, 1 player control, 2 computer control.') for name in ['player_control', 'enemy_control', 'force_2_control', 'force_3_control']], notes='Changes shared phase/control state. Restore all four values for the chapter when leaving a staged sequence.', types='byte byte byte byte')
define('_intr', 'Runs the chapter-checkpoint save sequence and suspends the calling script until it finishes.', returns='1 when scheduled; read MCResult for the card-operation status.', notes='Opens the memory card, writes the chapter checkpoint if opening succeeded, then closes it. Use only at a valid chapter save point; this is not a harmless pause.')
for name, direction in [('Tut3SArrowABAnim', 'positive diagonal'), ('Tut3SArrowBCAnim', 'horizontal'), ('Tut3SArrowCAAnim', 'negative diagonal'), ('Tut3SArrowDAnim', 'downward vertical'), ('Tut3SArrowUAnim', 'upward vertical')]:
    define(name, f'Continuously oscillates a tutorial arrow rectangle along its {direction} axis.', [R, ('period_ms', 'Positive oscillation period in milliseconds. Zero causes division by zero; do not pass 0.'), ('amplitude', 'Movement amplitude in screen coordinates; use a small positive value such as 4 or 6.')], VOID, 'The rectangle must exist first. The animation is attached to it and restores the original position when cleaned up; remove the rectangle to end the display.', 'charp int int')

# Keep examples self-contained when the generator wraps them in a function.
CONTRACTS['TTPMEntry']['args'][0] = ('path', 'Persistent direction string: 2 = down, 4 = left, 6 = right, 8 = up, one tile per character. Example: "66222". Stored by reference, not copied.')
define('SetEventBattle', 'Selects the special event presentation branch when the next battle animation is initialized.', [('enabled', '0 uses the ordinary presentation selection; nonzero overrides it with event presentation mode.')], notes='This is a shared scene setting, not a call that starts combat or forces damage. Set before NetuzoBattle and restore 0 after the staged battle.', types='byte')
ANIM = ('animation', 'Animation selector supported by this unit’s model/animation set. Use a selector from a matching unit; different models need not support the same animations.')
BLEND = ('blend_duration', 'Animation transition/blending length; UnitAnim uses 16. Zero requests an immediate switch once loaded; negative applies the animation immediately without the normal loading/wait process. This is not the length of the entire animation.')
define('UnitAnim', 'Loads and plays a unit animation with the default blend length of 16, replacing an existing scripted animation for that unit.', [U, ANIM], '1 when scheduled; 0 for an invalid unit or during skipping. The skip path still applies the animation immediately.', 'Use UnitMoveWait to synchronize with the scene’s motion/animation processes.', 'uint int')
define('UnitAnimF', 'Loads and plays a unit animation with a chosen transition length, replacing an existing scripted animation for that unit.', [U, ANIM, BLEND], '1 when scheduled; 0 for invalid unit, event skipping, or a negative blend duration. The latter two cases still apply the animation immediately.', 'The engine can increase the blend length for some current-animation categories, and can fall back to an immediate switch when too many animation layers exist.', 'uint int int')
